services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: ./config/.env
    restart: always
    command: ["sh", "-c", "python manage_db.py init && uvicorn main:app --host 0.0.0.0 --port 5000"]
    ports:
      - "5001:5000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    env_file: ./config/.env
    restart: always
    environment:
      LOCAL_API_KEY: ${LOCAL_API_KEY}
      BACKEND_API_URL: http://backend:5001/api
    ports:
      - "5002:8080"
    depends_on:
      - backend

  db:
    image: postgres:15
    env_file: ./config/.env
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
